services:
  - type: web
    name: nextjs-static
    env: static
    buildCommand: npm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: true # optional
    envVars:
      - key: NODE_ENV
        value: production
